### ISSUE TITLE
Cannot transcode files on Ubuntu 18.10 / Gnome Shell 3.30.1

### ISSUE THREAD

**Issue by logix2** [Rafostar/gnome-shell-extension-cast-to-tv#10]
Continuation of the second issue mentioned in https://github.com/Rafostar/gnome-shell-extension-cast-to-tv/issues/8

Transcoding doesn't work on my Ubuntu 18.10 / Gnome Shell 3.30.1 desktop. When I enable transcoding and I try to cast an OGV file, I get this error in a notification: "Error: load failed".

**Comment by Rafostar** [comment]
1. Check if you can transcode it from terminal.
```
ffmpeg -i video.ogv -c:v libx264 -pix_fmt yuv420p -preset superfast -level:v 4.1 -b:v 2M -maxrate 2M -c:a copy -f matroska output.mkv
```
2. You can also try running server app inside terminal and see if it logs you any errors during video selection and casting.
```
sudo killall node
cd ~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com
node node_scripts/server.js
```
Stop it later with `Ctrl + c`

3. If none of the above gives you any errors and you are using Chrome browser (video is transcoded into mkv which Firefox does not support), then try changing receiver type to "other" in extension settings, select file with transcoding enabled check mark and try playing it in browser at this link: [http://localhost:4000](http://localhost:4000)

Those are all options I could think of. The only other thing might be file rw permissions. Those are all wild guesses as I can not reproduce your problem on my side and you said in #8 that you were able to cast at least one file without transcoding so I assume that firewall is not blocking you.

**Comment by logix2** [comment]
I found out what's causing it, it was an issue with my system (sorry for wasting your time!). I had some old libavcodec, libavutil, etc. installed from the previous Ubuntu version (I upgraded to 18.10) and that was causing it. After removing those and a restart it works now.

**Comment by Rafostar** [comment]
No problem. I'm glad it works for you now.
