### ISSUE TITLE
[Feature Request] Subtitles choice

### ISSUE THREAD

**Issue by paulhewson** [Rafostar/gnome-shell-extension-cast-to-tv#112]
Hi therem U gave installed this extension on Ubuntu 19.10 / gnome 3.34 and everything works fine.
Just a question: I have a mkv video with incorporated subtitles in several languages.
It often happens that the first sub language is not english or italian (my mother tongue) but when casting this video to tv in only display the subs in the first language of the list. How can I choose the sub language when casting to tv?

Thank you

**Comment by Rafostar** [comment]
Hi,
Chromecast unfortunately does not support subtitles merged in a video container (hardware limitation). Currently the extension takes and converts first subtitle track found in video. In the future version I am planning to add some sort of selection when video has more that one subtitle track, but for now you have to extract the subtitles track of your choice manually and cast with those subs.

You can extract subtitles from terminal with `ffmpeg`.

1) Check available subtitles in video
```
ffmpeg -i "video.mkv" 2>&1 | grep Subtitle
```
You should see output like this:
```
    Stream #0:2(eng): Subtitle: ass (default)
    Stream #0:3(ara): Subtitle: ass
    Stream #0:4(fre): Subtitle: ass
    Stream #0:5(ger): Subtitle: ass
    Stream #0:6(ita): Subtitle: ass
    Stream #0:7(spa): Subtitle: ass
    Stream #0:8(por): Subtitle: ass
    Stream #0:9(rus): Subtitle: ass
```

Extract subtitle track of your choice with `-map` option:
```
ffmpeg -i "video.mkv" -map 0:6 subtitles.vtt
```

3) Add this subtitle file when casting or give it the same name as video file and copy it to "Extractor directory" set in extension preferences to have them added automatically.

**Comment by paulhewson** [comment]
The workaround works! Thank you for now!
Can't wait for the feature integration!

**Comment by Rafostar** [comment]
@paulhewson 
I did want to automate the subtitles selection, so I added options to write names of "preffered" and "fallback" languages to extension prefs. I am not gonna publish new version until gnome 3.36 support is resolved.

If you want to try it now install from latest git master and in preferences window go to `Other`->`Extractor` tab and set:
* Preferred language: `ita`
* Fallback language: `eng`

If you have saved subtitles in extractor save dir in prefs, remove them first, otherwise they will be detected and reused instead of extracting for that video again with correct language.

**Comment by paulhewson** [comment]
It works, man, I did a try with an episode of The Mandalorian which has encapsuled 10 different sub languages. It works!
Thank you!

**Comment by peguerosdc** [comment]
> 1. Add this subtitle file when casting or give it the same name as video file and copy it to "Extractor directory" set in extension preferences to have them added automatically.

How do you "add a subtitle file when casting"? Couldn't find any information about this neither in the wiki nor in the UI. Also, which formats are compatible (srt, vtt, other)?

**Comment by Rafostar** [comment]
@peguerosdc 
When using file selection (cast video from top GNOME menu) it will open a file select window. On this window select the video you wish to cast and click 2nd button on top right with text "Add subtitles". Then navigate to folder with your subtitles, select them and click "Cast selected file".

If you want to cast from file manager (with right click on file). Select exactly 1 video file and 1 subtitle file (in the same folder), right click and it should automatically cast with selected subtitles.

Right now supported subtitles extensions are: **srt, ass, vtt**
