### ISSUE TITLE
Cannot find node in PATH

### ISSUE THREAD

**Issue by blizarazu** [Rafostar/gnome-shell-extension-cast-to-tv#116]
Hi,

It doesn't find nodejs if it was installed using nvm. Node is in my path but I have to add a symlink in /usr/bin/node to my node executable so that this extension finds it.

Thank you.

**Comment by Rafostar** [comment]
@blizarazu 
This is normal. This is a GNOME Shell extension, so it runs as part of gnome-shell process. This means that it uses path of the user who started gnome-shell.

GNOME Shell is aware of local user $PATH. So it finds it if it was installed in `~/home/user/.local/bin` too, but it fails to do so if it was installed with `nvm`. The reason for that is probably that nvm adds it to the user $PATH after login. GNOME Shell is running before then and uses the path during launch.

There is probably nothing we can do about it in this case. The workaround you did is correct and I have mentioned this in [wiki](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv/wiki/Installation#npm-or-node-not-installed-message-in-extension-prefs) some time ago.

**Comment by blizarazu** [comment]
Thank you for the explanation and sorry that I didn't see the wiki.
