### ISSUE TITLE
Cast Off -> Can't turn on from the Shell system menu (Cast to TV v14)

### ISSUE THREAD

**Issue by logix2** [Rafostar/gnome-shell-extension-cast-to-tv#118]
Using Ubuntu 20.04, GNOME Shell 3.36.1 and Cast to TV v14, the Shell system menu shows "Cast Off", and when I click on "Turn on" nothing happens. I tried to restart the system, as well as a Cast to TV v14 clean install, but to no avail.

It does work if I run it like this though:

```
cd ~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts
DEBUG=bridge,chromecast* node server
```

But not from the GNOME Shell system menu. Opening the extension settings, which is mentioned not to work with GNOME Shell 3.36.1 in the Cast to TV v14 release notes, does work for me, I thought I'd mention this.

**Comment by logix2** [comment]
I found out why this happened. I had an old version of cast-to-tv-links-addon installed. After removing that, reinstalled Cast to TV v14, it worked. I then install the latest cast-to-tv-links-addon, and it continues to work.

**Comment by Rafostar** [comment]
@logix2 
Ah, that was the case. I had to change how addons are imported to make them work on 3.36. There are a lot of changes happening to gnome shell right now.

Ubuntu uses some older (more stable) packages than those on other distros like Arch Linux. In recent version of `gnome-shell-extension-prefs` tool GNOME devs removed ability to open prefs from a requested extension (and made a now extensions app), but a replacement function is queued for 3.36.2. Ubuntu might be using some older build of prefs tool that makes it still work, while on some distros with newer packages it does not.
