### ISSUE TITLE
Error when installing npm modules

### ISSUE THREAD

**Issue by marcelfarres** [Rafostar/gnome-shell-extension-cast-to-tv#120]
I try to install the modules and it fails under the next error. I am able to cast media anyway...

```
83 error code ELIFECYCLE
84 error syscall spawn
85 error file sh
86 error errno ENOENT
87 error bufferutil@4.0.1 install: `node-gyp-build`
87 error spawn ENOENT
88 error Failed at the bufferutil@4.0.1 install script.
88 error This is probably not a problem with npm. 
```
Running Ubuntu 20.04.

**Comment by Rafostar** [comment]
This is some kind of `node` install error. Maybe something went wrong during first install.

Try from terminal:
```
cd ~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com
rm -rf node_modules
npm install
```

**Comment by marcelfarres** [comment]
It worked :) Extremely useful to cast whatever you need.

Thank you very much!

PD: Extra question, do you know if it will be easy to implement to send to speaker group? or split the audio and the video to 2 different devices?

**Comment by Rafostar** [comment]
> It worked

:+1: 

> PD: Extra question, do you know if it will be easy to implement to send to speaker group? or split the audio and the video to 2 different devices?

Splitting audio and video to 2 different devices and keeping them in sync is probably not possible.

Casting MUSIC to audio groups should be possible. According to Google documents when you configure an audio group, its "master" device should show up in scan results and casting music to it should (probably) make the whole group play it. I only own a single Chromecast device, so I cannot test such feature myself and if it does not work cannot fix it.
