### ISSUE TITLE
Error opening Cast Settings - Vte not found

### ISSUE THREAD

**Issue by jsuarez314** [Rafostar/gnome-shell-extension-cast-to-tv#125]
I get this error,
Error: Requiring Vte, version none: Typelib file for namespace 'Vte' (any version) not found

when try to open the Cast Settings.

**Comment by Rafostar** [comment]
Your linux distro name?

**Comment by jsuarez314** [comment]
Sorry,

Debian 10 (Buster)
npm 6.14.7
Gnome Shell 3.30.2

**Comment by Rafostar** [comment]
You are missing `GI Vte` bindings package. I do not use Debian, so I am not entirely sure, but i think that the correct package you have to install is `gir1.2-vte-2.91`.
```
sudo apt-get install gir1.2-vte-2.91
```

**Comment by jsuarez314** [comment]
It's works for me. Thanks!
