### ISSUE TITLE
Casting Videos and Desktop not working

### ISSUE THREAD

**Issue by stuaxo** [Rafostar/gnome-shell-extension-cast-to-tv#128]
1. After a fresh install of this extension and it's node modules from extension prefs, usually a reboot fixes this issue (and by reboot I mean full system reboot - not just restarting gnome-shell).

2. Make sure you have receiver type in extension prefs set correctly to desired device type (e.g. "Chromecast"). If it wasn't try casting again.

3. If extension seems to be working (you have a top panel drop down menu), but still experiencing problems with casting, lets take a look at what happens during file cast. Turn off this extension node service without disabling whole extension (from gnome top bar menu). TV indicator icon should disappear from top bar. Then do the following in terminal:

```
cd ~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts
DEBUG=bridge,chromecast* node server
```

After running, extension menu and indicator should reappear.
Try reproducing your problem and send me output. Stop the terminal process with Ctrl+c buttons.

Output:
```
  bridge Full playlist: ["/home/stu/Videos/Peek 2018-04-20 16-44.webm"] +0ms
  bridge New selection contents: {"streamType":"VIDEO","subsPath":"","filePath":"/home/stu/Videos/Peek 2018-04-20 16-44.webm"} +1ms
  bridge Processing video file... +0ms
  bridge No reusable subtitles file +2ms
  bridge No merged subtitles found +78ms
  bridge File processed successfully +1ms
  chromecast NEW SELECTION +0ms
  chromecast Generated new session id: 9O4bEux5ie +11ms
  chromecast Media title: Peek 2018-04-20 16-44 +0ms
  chromecast Setting media: {"contentId":"http://192.168.178.31:4000/cast?session=9O4bEux5ie","contentType":"video/*","streamType":"BUFFERED","metadata":{"metadataType":1,"images":[{"url":""}],"title":"Peek 2018-04-20 16-44"}} +1ms
  chromecast Setting opts: {"autoplay":false,"activeTrackIds":[],"name":"17c2415c-1605-9395-1b7b-2c29e49b7286.local","ip":null} +0ms
  chromecast Casting... +0ms
  chromecast-controller Player check: inactive +0ms
  chromecast-controller Starting new cast session... +0ms
  chromecast-controller Searching for device: 17c2415c-1605-9395-1b7b-2c29e49b7286.local +0ms
  chromecast-controller Found device ip: 192.168.178.24 +119ms
  chromecast Could not cast: Launch failed. Reason: CANCELLED +1s
  chromecast Error: Launch failed. Reason: CANCELLED
  chromecast     at /home/stu/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_modules/castv2-client/lib/controllers/receiver.js:51:23
  chromecast     at fn.onmessage (/home/stu/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_modules/castv2-client/lib/controllers/request-response.js:27:7)
  chromecast     at emitTwo (events.js:131:20)
  chromecast     at fn.emit (events.js:214:7)
  chromecast     at Channel.onmessage (/home/stu/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_modules/castv2-client/lib/controllers/controller.js:16:10)
  chromecast     at emitTwo (events.js:126:13)
  chromecast     at Channel.emit (events.js:214:7)
  chromecast     at Client.onmessage (/home/stu/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_modules/castv2/lib/channel.js:23:10)
  chromecast     at emitMany (events.js:152:20)
  chromecast     at Client.emit (events.js:224:7) +0ms
  chromecast Unhandled message: launch failed. reason: cancelled +0ms
```

Initially casting didn't work at all, it turns out `nomachine` was running on port 4000, and this stopped things running:
- could CastToTV display some visible error somewhere if it can't get the desired port ?
- could it either move to another port, or try a range ?

I tried casting a Video and got the output above,
The TV flashed for a moment, but didn't play the video.

In the settings I tried the option to detect devices, it shows "Android TV", correctly, but it has IP as "None", which doesn't seem right.

**Comment by Rafostar** [comment]
@stuaxo 
So after you changed port cast started working?

> In the settings I tried the option to detect devices, it shows "Android TV", correctly, but it has IP as "None", which doesn't seem right.

It is correct. When device was detected on scan it should have an "Auto" tick-mark next to it. When it does, the IP can be left empty and it will be automatically detected when you start a cast. This is one of the features this extension has. We do not need to waste time to scan network for all devices after each app start.

**Comment by stuaxo** [comment]
After I changed port, cast didn't start working, it started working enough to make the TV flash once and give the output I pasted above when trying to play a Video, trying to cast the desktop did nothing.

**Comment by stuaxo** [comment]
Casting videos and links seems to working now, I changed the listening port to 4001.

I'm not quite sure how to get desktop casting working.

**Comment by stuaxo** [comment]
I just noticed that if you click settings, it opens a new settings window every time, it would be good if it could focus the open settings window if it's already open.

**Comment by Rafostar** [comment]
What is your GNOME Shell version?

**Comment by stuaxo** [comment]
3.36.4

**Comment by Rafostar** [comment]
On 3.36 we use a GNOME provided function to open settings window. I will have to check the open settings behaviour.

As for desktop streaming... Did you set correct audio plugin in desktop settings and installed all gstreamer plugins as described in desktop add-on [README](https://github.com/Rafostar/cast-to-tv-desktop-addon)?

**Comment by stuaxo** [comment]
Ah, good catch - I'm not sure which package under ubuntu provides gstreamer fdkaac gstreamer faac + gst-inspect shows them not installed.

I've installed:

`gstreamer1.0-vaapi gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly`

**Comment by stuaxo** [comment]
It would be pretty handy if inside the UI it would grey out the menu options for codecs that can't be found by gstreamer.

**Comment by stuaxo** [comment]
I only just noticed the desktop notification:  Cast to TV could not start desktop recording.

**Comment by Rafostar** [comment]
> It would be pretty handy if inside the UI it would grey out the menu options for codecs that can't be found by gstreamer.

Good idea. I will add that once I resume the extension development.

> I'm not sure which package under ubuntu provides gstreamer fdkaac

fdkaac gives best audio quality, but unfortunately it is unavailable on Ubuntu. You have to install `gstreamer1.0-libav` and select "AVENC AAC".

**Comment by Rafostar** [comment]
@stuaxo 
Did you get it to work?

**Comment by stuaxo** [comment]
Cool, tried it just now and it work - but so far only with no hardware acceleration, there are about 10 seconds of lag, is that normal over Wifi ?

I changed the settings and it got into a weird state where I couldn't get Cast-Off to work any more (so that the menu then Displays Cast-On), and the current selection seemed to want to be Cast-Media even though I'd been attempting to Cast-Desktop.

EDIT:  I just noticed it continued to say "Cast-Media" even while I was casting the desktop.

**Comment by Rafostar** [comment]
> Cool, tried it just now and it work - but so far only with no hardware acceleration, there are about 10 seconds of lag, is that normal over Wifi ?

At the current development state, this is the best we have.

> EDIT: I just noticed it continued to say "Cast-Media" even while I was casting the desktop.

This is just the menu name. The cast desktop option should be inside it.

**Comment by stuaxo** [comment]
>>    Cool, tried it just now and it work - but so far only with no hardware acceleration, there are about 10 seconds of lag, is that normal over Wifi ?
> At the current development state, this is the best we have.
Fair enough :)

> This is just the menu name. The cast desktop option should be inside it.
I though it would show the currently casting thing, as when casting is off it shows "cast off".

In theory can I get hardware acceleration working when casting the desktop ?

Cool, I reckon I will shut this now, thanks for cast-to-tv.

**Comment by Rafostar** [comment]
> In theory can I get hardware acceleration working when casting the desktop ?

In theory, yes. If your GPU is capable of hardware accelerated **recording** (encoding). Mine is not, so I have not tried it personally.

**Comment by stuaxo** [comment]
Cool, I think I'd probably need to have a play with that outside of cast-to-tv to reduce the amount of variables to see if that's possible, though might be a while until I get time.

S++ 

    On Monday, October 12, 2020, 6:28:47 PM GMT+1, Rafostar <notifications@github.com> wrote:  
 
 



In theory can I get hardware acceleration working when casting the desktop ?


In theory, yes. If your GPU is capable of hardware accelerated recording (encoding). Mine is not, so I have not tried it personally.

**Comment by stuaxo** [comment]
I followed this guide -
http://lifestyletransfer.com/how-to-install-gstreamer-vaapi-plugins-on-ubuntu/

It was quite handy, pretty quickly I could see from `vainfo` that VAAPI wasn't working.

`apt install va-driver-all` seemed to get it working (in particular, that installed `mesa-va-drivers`)

I haven't been able to actually test Desktop streaming yet as my 3 year old is now monopolising the TV.


There are some small scripts in the page above that may be good to adapt as sanity checks, if the user selects VAAPI (or maybe just after VAAPI fails).
