### ISSUE TITLE
[Feature Request] Cast desktop on Gnome Wayland

### ISSUE THREAD

**Issue by devmrfitz** [Rafostar/gnome-shell-extension-cast-to-tv#133]
Is it possible to allow casting the entire desktop on Gnome Wayland? Lag isn't an issue if audio is in-sync with video

**Comment by Rafostar** [comment]
Yes. There is a separate add-on that does that, but as of now it does not work with latest GNOME 3.38:
[https://github.com/Rafostar/cast-to-tv-desktop-addon](https://github.com/Rafostar/cast-to-tv-desktop-addon)

If you have any other issues with desktop casting, please open them on that add-on github page.
