### ISSUE TITLE
Chromecast device not found

### ISSUE THREAD

**Issue by T3sT3ro** [Rafostar/gnome-shell-extension-cast-to-tv#138]
So the Chromecast can't find my TV. Manually specifying device IP (`192.168.0.102` was the IP of my LG TV) still nothing happens. Running built-in cast from chrome somewhat works - it can see the TV on the list and I can cast for example YouTube from. This means, that there is something wrong with detecting chromecast devices. I tried casting desktop, image and video.

I manually (even though I probably didn't have to) changed iptables as wiki instructs. 

My setup uses a laptop connecting to wifi and LG TV connected to the same network via ethernet cable.

1. After a fresh install of this extension and it's node modules from extension prefs, usually a reboot fixes this issue (and by reboot I mean full system reboot - not just restarting gnome-shell). - **did that, doesn't work**

2. Make sure you have receiver type in extension prefs set correctly to desired device type (e.g. "Chromecast"). If it wasn't try casting again.

3. If extension seems to be working (you have a top panel drop down menu), but still experiencing problems with casting, lets take a look at what happens during file cast. Turn off this extension node service without disabling whole extension (from gnome top bar menu). TV indicator icon should disappear from top bar. Then do the following in terminal:

```
cd ~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts
DEBUG=bridge,chromecast* node server
```

After running, extension menu and indicator should reappear.
Try reproducing your problem and send me output. Stop the terminal process with Ctrl+c buttons.

Output:
```
  bridge Full playlist: ["Desktop Stream"] +0ms
  bridge New selection contents: {"addon":"DESKTOP","title":"Desktop Stream","streamType":"LIVE","hlsStream":false,"tcpPort":4007,"maxLiveDelay":7,"filePath":"Desktop Stream"} +1ms
  bridge Starting desktop add-on... +0ms
  bridge Send selection to add-on +0ms
  chromecast NEW SELECTION +0ms
  chromecast Generated new session id: nMH91YHqDl +7ms
  chromecast Media title: Desktop Stream +0ms
  chromecast Setting media: {"contentId":"http://192.168.0.117:4000/cast?session=nMH91YHqDl","contentType":"video/*","streamType":"LIVE","metadata":{"metadataType":1,"images":[{"url":""}],"title":"Desktop Stream"}} +0ms
  chromecast Setting opts: {"autoplay":true,"activeTrackIds":[],"name":null,"ip":null} +0ms
  chromecast Casting... +0ms
  chromecast-controller Player check: inactive +0ms
  chromecast-controller Starting new cast session... +0ms
  chromecast-controller Searching for any device +0ms
  chromecast Could not cast: device not found +22s
  chromecast Error: device not found
  chromecast     at Timeout.setTimeout (/home/tooster/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_modules/multicast-scanner/index.js:27:10)
  chromecast     at ontimeout (timers.js:436:11)
  chromecast     at tryOnTimeout (timers.js:300:5)
  chromecast     at listOnTimeout (timers.js:263:5)
  chromecast     at Timer.processTimers (timers.js:223:10) +0ms
Chromecast: Device not found

```

**Comment by Rafostar** [comment]
This output is from when device IP was not set. Can you do similar output after manually specifying Chromecast device IP?

**Comment by T3sT3ro** [comment]
I think I may have been misinformed - my TV probably doesn't use Chromecast but Miracast (`LG webOS TV sk8100PLA`) for what I have been able to test. I'm not sure if I'll be able to make it work with this extension - I'll be trying with some miracast-centric programs. I see that there are 3 types of receiver types and this link on the bottom of options menu "Access web player from devices on local network", but whatever I try doesn't seem to connect to the TV in any way. I'm pretty sure that it's not TV's fault, because Windows' "cast to device" works flawlessly. Am I missing something? Should this extension work with Miracast somehow?

**Comment by Rafostar** [comment]
@T3sT3ro 

Chromecast and Miracast are totally different protocols. This extension aims at Chromecasts (including TVs with build-in Google Cast functionality), so Chromecast option will not work with Miracast.

There is an option to cast to web browser, one would have to select it as receiver type in extension settings, open web browser on destination device with the URL shown on extension prefs then cast. This needs a HTML5 capable browser. Not sure what the build-in browser in LG webOS is capable.

If you want something that works with Miracast then you will have to look elsewhere.
