### ISSUE TITLE
Incomplete Italian translation

### ISSUE THREAD

**Issue by Rafostar** [Rafostar/gnome-shell-extension-cast-to-tv#14]
I would like to do next version release soon, but Italian translation was not updated in a long time and is incomplete. Can someone help by updating `it.po` file?

@amivaleo If you are still interested in this project could you do an update for me? Thanks.

**Comment by amivaleo** [comment]
Done, sir! :)

**Comment by Rafostar** [comment]
Fixed by #15 Thanks again.
