### ISSUE TITLE
Choose device

### ISSUE THREAD

**Issue by maskaz** [Rafostar/gnome-shell-extension-cast-to-tv#146]
Hi. Is there a way to choose device (if there are more than one) where media files will cast (by CLI or by sending request to server) without need to open config window every time? 

Regards

**Comment by Rafostar** [comment]
Yes. This is described in the wiki: [chromecast-options](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv/wiki/Configuration#chromecast-options)

Either use auto scanner manually configure devices IPs. If you have more then one device a list of devices to select will appear when you right click on a media file.

**Comment by maskaz** [comment]
Yes, but i cannot force it to work (option under right clickmenu in nautilus).
G_MESSAGES_DEBUG="all" NAUTILUS_DEBUG="Window" nautilus doesn't show any error, but this extension does not wanna show up (other works), that is why i'm asking about alternative.

**Comment by maskaz** [comment]
I do not know why, something was wrong with python file(nautilus extension) i had download it again manualy and now works!
Thank you very much for your work!
