### ISSUE TITLE
CLI version?

### ISSUE THREAD

**Issue by rwjack** [Rafostar/gnome-shell-extension-cast-to-tv#149]
Hi,
Do you have any intentions of releasing a CLI version? My idea was to have my headless server be able to stream files to the TV.

I'm not really a JS expert, but out of all the linux/chromecast projects yours seems to be the most up to date/maintained, so I'd be willing to lend a hand if we could make this happen :)

**Comment by Rafostar** [comment]
For a headless server, you should be able to clone the project, install node modules from cmd, run `node server.js` script as main entrypoint, then post the HTTP requests to your headless device from other (or oven the same) device with data what file to play. See [wiki#web-api](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv/wiki#web-api) for a few simple examples.

**Comment by rwjack** [comment]
Gotcha, I'll give it a shot.
