### ISSUE TITLE
"nodejs is not installed" even though node is installed with N package manager

### ISSUE THREAD

**Issue by T3sT3ro** [Rafostar/gnome-shell-extension-cast-to-tv#150]
Trying to install and configure the addon results in a window saying "nodejs is not installed". This is true, because `nodejs` is missing from the PC, but I don't want to use it as I am running the N package manager to manage my node installations. I tried creating softlinks `nodejs` in the same directory as `which node`, `/usr/local/bin`, but it still says `nodejs` is missing. I recall that before I removed preinstalled `node` and `nodejs` from my system the addon kinda worked.

OS info:
```
tooster@toosterLap 
------------------ 
OS: Ubuntu 20.04.3 LTS x86_64 
Host: 81FL Lenovo ideapad 330-17ICH 
Kernel: 5.4.0-91-generic 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: GNOME 
WM: Mutter 
WM Theme: Yaru-dark 
Theme: Yaru-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-8750H (12) @ 2.200GHz 
GPU: NVIDIA GeForce GTX 1050 Mobile 
GPU: Intel UHD Graphics 630 
Memory: 4557MiB / 19892MiB 
```

**Comment by Rafostar** [comment]
See https://github.com/Rafostar/gnome-shell-extension-cast-to-tv/issues/79 for what worked for others in similar situation.

**Comment by T3sT3ro** [comment]
Hmm, creating a link from `/usr/bin` worked, but from the `/usr/local/bin` didn't. Thanks, anyway.
