### ISSUE TITLE
Translations status and requests

### ISSUE THREAD

**Issue by Rafostar** [Rafostar/gnome-shell-extension-cast-to-tv#29]
<p align="center">
  <b>Translations Status ->
      <a href="https://crowdin.com/project/cast-to-tv">Cast to TV - Crowdin</a>
  </b>
</p>

Please update translations if you do not want to see your language mixed with English in next release.

I am always happy to add additional languages. If you want to become a translator for missing language, let me know in comments below (I must add new language to Crowdin first).

Using Crowdin for updating translations is preferred, otherwise please use an editing app like `Poedit` for generating files and not do it in plain text editor.

**Comment by Vistaus** [comment]
Hi,

Could you add Dutch please? :-)

**Comment by Rafostar** [comment]
Dutch added :+1:

**Comment by Vistaus** [comment]
> Dutch added

Thank you! :)

**Comment by 1989gironimo** [comment]
I'd like to translate the app to german!

**Comment by Rafostar** [comment]
> I'd like to translate the app to german!

German added :+1:

**Comment by jsuarez314** [comment]
I can to make the Spanish translation!

**Comment by vladut3pg** [comment]
Hey,
Can you add Romanian? :smile:

**Comment by xedsvg** [comment]
Hey,
Can you add Romanian? :smile:

**Comment by Rafostar** [comment]
@xedsvg 
Added Romanian. It unfortunately won't be included in recently released v12, that is pending review on Gnome extensions website. :-( I will probably do a next bug-fix release in near future through.

**Comment by Rafostar** [comment]
@xedsvg @vladut3pg
The Romanian language was added to Crowdin, but nobody translated to it. Adding new lang to Crowdin automatically generates a PR with all untranslated English strings.

I do not speak Romanian and I am not going to bloat everyone's shells with loading of hundreds completely untranslated lines. If nobody is willing to translate into Romanian before next release, the language will be removed from Crowdin page. Thank you for understanding.

Also continuing this thread anymore is pointless. If somebody else wants a new translation please either message me on Crowdin directly or open a new issue using template I created.
