### ISSUE TITLE
[feat] add a way to start / stop the service

### ISSUE THREAD

**Issue by CircleCode** [Rafostar/gnome-shell-extension-cast-to-tv#35]
as soon as the extension is enabled, the server is started.
Even if it is not heavy when idle, it would be interesting to start it only when needed to avaoid unnecessary processes.

**Comment by Rafostar** [comment]
As you mentioned the process is not CPU heavy (zero usage when idle), but still eats some ram when running. It is possible, but it would also mean altering nautilus extension to not display menu when disabled and hiding menu items (process needs to be started before file selection is made).

What do you think the most convenient way to toggle it would be? I think that maybe adding 'Turn Off' menu item like the one on Ethernet and WiFi settings (keep it consistent with Gnome design) would be good.

**Comment by CircleCode** [comment]
> It is possible, but it would also mean altering nautilus extension to not display menu when disabled and hiding menu items (process needs to be started before file selection is made).

I suppose that it would not be possible to start the server on file selection, and then do whatever is needed to cast it ?
In that case, what about not hiding but disabling nautilus menu entries (with some message like *server not running*) to avoid the *magical* appearance / disappearance of them?

> What do you think the most convenient way to toggle it would be? I think that maybe adding 'Turn Off' menu item like the one on Ethernet and WiFi settings (keep it consistent with Gnome design) would be good.

I totally agree with this solution, it is clear, and is consistent with what users are used to.
Also, when server is disabled, it should be visible in the title of the collapsible *Cast Media* entry (for example : *Cast Media Off*

**Comment by Rafostar** [comment]
> I suppose that it would not be possible to start the server on file selection, and then do whatever is needed to cast it ?

Unfortunately that won't be possible. Server needs to be started first, then it waits for user selection before it takes action. On previous versions I had server startup done in background when user opened file-chooser, but it had problem that on slower pc node takes some time to start and if user made selection too quick (before it finished starting) casting did not work. Besides this time we have nautilus integration so there is no guarantee that entries from top bar drop down menu will be used at all and starting server before each cast would make waiting for content delivery much longer.

> In that case, what about not hiding but disabling nautilus menu entries

Not showing nautilus menu entry is fine. It is not shown when right clicked on non media file anyway. By hiding menu items I meant those from Gnome top bar Cast Media menu. There would be no point in showing them on _Cast Media Off_ state.
