### ISSUE TITLE
Add various infos to docs

### ISSUE THREAD

**Issue by 1989gironimo** [Rafostar/gnome-shell-extension-cast-to-tv#43]
- Needed firewall rules if the connection doesn't work:
`iptables -I INPUT -p udp --dport 5353 -j ACCEPT` for MDNS (automatic detection of a Chromecast device)
`iptables -I INPUT -p udp -m udp --dport 32768:61000 -j ACCEPT` (Needed for Chromium, maybe for casting via the addon as well?)
`iptables -I INPUT -p tcp --dport 4000 -j ACCEPT` (Needed for streaming to Chromecast device)

- Maybe it's necessary to inform that Wayland isn't supported (for the desktop-casting-addon) at this time.

- A link to the config tool would be nice as well, if somebody runs into a problem discovering their devices.

- A link to the experimental desktop-casting addon, maybe to give the users a hint to test this functionality under different conditions

**Comment by 1989gironimo** [comment]
A link to the config tool would be nice as well, if someone runs into the problem with the discovery of their devices.

**Comment by Rafostar** [comment]
* Firewall config has been added to the [wiki](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv/wiki/Firewall-rules)
* Mentioned required X11 session and resolution on desktop-addon github page
* Added use case to cast-to-tv-config link in readme
* Added links to experimental add-ons
