### ISSUE TITLE
noob question - make file target?

### ISSUE THREAD

**Issue by ldnelso2** [Rafostar/gnome-shell-extension-cast-to-tv#51]
Hi - I downloaded the files for my appropriate GNOME shell version, but the installation instructions look like you have to do a make install.  what am I missing?

make: *** No targets specified and no makefile found.  Stop.

**Comment by Rafostar** [comment]
> Hi - I downloaded the files for my appropriate GNOME shell version

I have not dropped any GNOME version support in any release, so you should always use the latest version.

> make: *** No targets specified and no makefile found. Stop.

`make install` needs to be run inside downloaded dir (where file named Makefile is).

But the easiest way to install is from [gnome extensions website](https://extensions.gnome.org/extension/1544/cast-to-tv), so if your browser allows installing from that site I recommend it.

Also remember that you need npm, nodejs and ffmpeg installed on your system prior to using this extension.

**Comment by Rafostar** [comment]
Wait, did you download from gnome shell extensions website by selecting version? If yes, then there is no Makefile in their zip. Extensions from that site should by enabled by **pressing on/off button** instead. Makefile can only be found if you download from github releases page or install from latest git code.

**Comment by ldnelso2** [comment]
Yes, thats corrrect.  I downloaded it with the zip file, installed the extension and the dependencies.  Where would be the on/off button be?  I really apologize as I'm sure this is obvious, but I have been looking and just can't seem to figure it out.

**Comment by Rafostar** [comment]
![extension switch](https://user-images.githubusercontent.com/40623528/60621568-4a845d80-9dde-11e9-9b30-7ee14df36493.png)

**Comment by ldnelso2** [comment]
Okay, now I got it.  I'm sorry, just wasn't readily apprent, super easy now that you showed me.  Thanks!

I am going to go ahead and close out the issue.
