### ISSUE TITLE
Logo proposal 

### ISSUE THREAD

**Issue by memoryskull** [Rafostar/gnome-shell-extension-cast-to-tv#52]
Hi @Rafostar 
I'm interested in collaborating with this project by delivering a series of logotype options that fits this project for the best!

If interested let me know so we can get started!

Cheers!

**Comment by Rafostar** [comment]
I am fine with stock cast logo that this project currently uses. So thanks, but no thanks.

BTW: User who claims that he can draw over 20 logos at once for different unrelated projects fills a little spammy... Even if your good intentions might be true.
