### ISSUE TITLE
Cannot transcode video with subtitles because of a ' in my video folders name e.g. Video's

### ISSUE THREAD

**Issue by RobRobM** [Rafostar/gnome-shell-extension-cast-to-tv#53]
Transcoding a video does not work from my default video folder because of a ' in its name (Video's). 

I'm using a symbolic link to the folder as a workaround.

**Comment by Rafostar** [comment]
This is one of chars that does not work correctly when passed to ffmpeg `subtitles` video filter (even when escaped with `\` sign). If you manage to correctly run something like below from terminal, let me know and I will gladly fix this in my app.

```
ffmpeg -i video.mkv -vf subtitles=/path/to/video\'s/subs.srt out.mkv
```

Interesting is the fact that video path works correctly with `'` sign when escaped, but not subtitles filter. Unless there is something I do not know about, it seems like it is a ffmpeg bug. If this is important to you please report this to ffmpeg devs.

**Comment by RobRobM** [comment]
No worries. I have a work around. I'll inform ffmpeg Devs about this bug.

Thanks again for the work and quick reply.
