### ISSUE TITLE
Subtitles are shown at the top of the screen when casting to a Chromecast

### ISSUE THREAD

**Issue by RobRobM** [Rafostar/gnome-shell-extension-cast-to-tv#54]
When casting to a Chromecast (Ultra) subtitles are shown at the top of the tv, even a bit out of view. This happens when NOT transcoding, just casting the video with subtitles.

Ps. Thanks for the hard work ;-)

**Comment by Rafostar** [comment]
Unfortunately Google broke subtitles in recent Chromecast update. According to [this](https://support.google.com/chromecast/thread/7612416) and [this](https://support.google.com/chromecast/thread/9414923) thread, Google is aware of the problem and promises to fix it "soon". It affects other apps besides this extension too.

> Ps. Thanks for the hard work ;-)

Thanks! Sorry I couldn't help you. The only thing we can do is wait for Google to fix this :disappointed:
