### ISSUE TITLE
Nvidia hardware acceleration

### ISSUE THREAD

**Issue by Rafostar** [Rafostar/gnome-shell-extension-cast-to-tv#60]
I would like to add NVENC hardware video transcoding. Unfortunately I do not own any device with Nvidia GPU. It can be added if someone having *Kepler* or newer GPU with Nvidia proprietary drivers will be willing to do few simple tests from command line.

Here is what needs to be tested:
1. Encoding video that does not have muxed (built-in) subtitles:
```
ffmpeg -i 'video.mkv' -c:v h264_nvenc -level:v '4.1' -b:v 4M -c:a copy output.mkv
```

2. Encoding video that has muxed (built-in) subtitles:
```
ffmpeg -i 'video.mkv' -c:v h264_nvenc -vf subtitles=video.mkv -sn -level:v '4.1' -b:v 4M -c:a copy output.mkv
```

3. Encoding video with external subtitles file:
```
ffmpeg -i 'video.mkv' -c:v h264_nvenc -vf subtitles=videoSubtitles.srt -sn -level:v '4.1' -b:v 4M -c:a copy output.mkv
```

These are the simplest ffmpeg commands I could think of (only for testing purposes).

Please let me know if all of the above commands are working correctly (use them in terminal in the same folder where video is and make sure that tested video and subtitles files DO NOT include spaces or special chars). After video encoding process starts wait a few seconds and press *q* key. Then check if you can play newly created **output.mkv** file in your media player app.

If any of the above commands does not work and you are aware of additional options that need to be passed to ffmpeg to make it work, please share in comments below.

**Comment by Rafostar** [comment]
I have added initial support for NVENC to extension, but it is untested (lack of Nvidia GPU), so I will not enable it until someone does the above tests for me.

**Comment by deisi** [comment]
I have the following Nvidia Card. I think I could run your tests.

01:00.0 3D controller: NVIDIA Corporation GP108M [GeForce MX150] (rev ff)
However this is on my laptop and uses thus Optimus. I would first need to find out how to activate the card for my normal desktop. 
I further have a tower pc with a gtx1070. I could put say Ubuntu on that one and test as well.

**Comment by deisi** [comment]
I just tried the first command and I get Unknown encoder 'h264_nvenc'
I then checked it out a little and I find https://bugs.launchpad.net/ubuntu/+source/ffmpeg/+bug/1828082
so it seems that on Ubuntu 19.04 this will not work out of the box.

**Comment by deisi** [comment]
After compiling ffmpeg manually I now have a version with nvenc compiled into it.

> Encoding video that does not have muxed (built-in) subtitles:

Worked perfectly.

> Encoding video that has muxed (built-in) subtitles:

Worked as well. 

> ffmpeg -i 'video.mkv' -c:v h264_nvenc -vf subtitles=videoSubtitles.srt -sn -level:v '4.1' -b:v 4M -c:a copy output.mkv

is correct as well.

**Comment by Rafostar** [comment]
Thank You! Can you try casting the output files to Chromecast to confirm that it can actually play them as they are (without using transcoding in extension).

**Comment by deisi** [comment]
Okay, I casted all of the videos and all of them worked. From my point of view it is a go.
However I'm not sure I understand what you mean with 

> without using transcoding in extension

as I thought the addon has no transcoding. I also couldn't find any transcoding setting. The only thing I found was Hardware acceleration under Media Encoding and this I turned to None.

**Comment by Rafostar** [comment]
OK, thanks for testing.

The transcoding setting in extension does not enable transcoding by itself. You either have to tick the checkbox at bottom left corner in file chooser dialog or select transcode video if casting from Nautilus right click menu. Different Chromecast models support different media types (eg. model 3 has 60fps, Ultra 4k etc.). That is why I decided to make it a manual choice (scan does not detect model).

For more info how this extension works check the extension [wiki](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv/wiki).

**Comment by deisi** [comment]
Ah now I found the transcoding button. Neat.
