### ISSUE TITLE
Remote control vanishes without stopping playback

### ISSUE THREAD

**Issue by deisi** [Rafostar/gnome-shell-extension-cast-to-tv#65]
I  have experienced problems with the build in remote control. It frequently doesn't stop the cast and vanishes. Maybe one could in cooperate https://extensions.gnome.org/extension/1955/cast-control/ as this seems to work a lot better.

**Comment by Rafostar** [comment]
> It frequently doesn't stop the cast

Can you give me a little more detail (or example so I can try to reproduce this problem)? Do you mean that during local video or music you were just playing you pressed stop and nothing happened?

**Comment by deisi** [comment]
Okay, I found a way to reproduce the problem. 
When I cast a video that has vp9 as video and mpeg 4 - aac for audio I only get audio. Then I use the remote to stop the cast, because I see no video. However the audio doesn't stop, instead it keeps playing and the remote vanishes.

**Comment by Rafostar** [comment]
As I said to you earlier [in desktop issue](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv/issues/5#issuecomment-526824239), Chromecast does not support VP9. I will try improving this behaviour on stream error, but this will not change the fact that Chromecast simply is unable to play it.

**Comment by deisi** [comment]
yes I know, I'm not worried about the vp9 issue. Just that the remove vanishes and doesn't work in these kind of situations.

**Comment by deisi** [comment]
In case you need a test file: https://ufile.io/ozfvn352

**Comment by deisi** [comment]
I just experienced the same with a valid file. I was playing it for some time, and then I wanted to stop it. Clicked the stop button on the remote and nothing happened. This time it was a valid file. At least video and audio was playing just fine.

**Comment by Rafostar** [comment]
What OS are you using? Did you install from git master (if not please remove cast-to-tv extension folder in `~/.local/share/gnome-shell/extensions` and reinstall from git)?

After you are set up with latest git master (and npm modules installed), turn off this extension service (from this extension top bar menu). TV indicator icon should disappear from top bar. Then do the following:

```
cd ~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts
DEBUG=bridge,chromecast node server
```

After running, extension menu and indicator should reappear.
Try reproducing your problem and send me output. Stop the terminal process with `Ctrl+c` buttons.

TIP: you can pipe the output to file by adding `&> cast.log`. Send me that file then.

**Comment by deisi** [comment]
> What OS are you using? 

Ubuntu 19.04

> Did you install from git master

yes

```
malte@malte-desktop:~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts$ DEBUG=bridge,chromecast node server
^C
Closing Cast to TV...
  bridge Closing node server +0ms
  bridge Closed file watcher +2ms
  bridge Removed top bar indicator +8ms
  bridge Cleaned selection temp file +0ms
Cast to TV closed successfully
malte@malte-desktop:~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts$ DEBUG=bridge,chromecast node server
  bridge New playlist contents: ["/home/malte/Videos/output.mkv"] +0ms
  bridge New selection contents: {"streamType":"VIDEO","subsPath":"","filePath":"/home/malte/Videos/output.mkv","transcodeAudio":false} +50ms
  chromecast NEW SELECTION +0ms
  chromecast Waiting for extract processes to finish... +0ms
  chromecast Processes finished extracting +101ms
  chromecast Generated new session id: mzA8FCtobb +7ms
  chromecast Media title: output +0ms
  chromecast Setting opts: {"path":"http://172.16.1.31:4000/cast?session=mzA8FCtobb","type":"video/*","streamType":"BUFFERED","autoplay":false,"activeTrackIds":[1],"media":{"textTrackStyle":{"backgroundColor":"#00000000","foregroundColor":"#FFFFFFFF","edgeType":"OUTLINE","edgeColor":"#000000FF","fontScale":"1.0","fontStyle":"NORMAL","fontFamily":"Droid Sans","fontGenericFamily":"SANS_SERIF","windowType":"NONE"},"tracks":[{"trackId":1,"type":"TEXT","trackContentType":"text/vtt","name":"Subtitles","subtype":"SUBTITLES","trackContentId":"http://172.16.1.31:4000/subswebplayer?session=mzA8FCtobb"}],"metadata":{"metadataType":"GENERIC","title":"output"}},"device":null,"address":null,"ttl":4000} +0ms
  chromecast Launching new cast session... +1ms
  chromecast Launched new session +4s
  chromecast Performing new session status check... +0ms
  chromecast New session OK +0ms
  chromecast Started status interval +0ms
  chromecast Starting delayed playback... +1ms
  chromecast Obtained volume value: 1 +3ms
  chromecast Playback started +3s
  bridge New remote contents: {"action":"STOP"} +16s
  chromecast Signal from remote. ACTION: STOP +10s
  chromecast Stopped status interval +1ms
  chromecast Closing cast session... +0ms
  chromecast Session closed +2ms
  chromecast Cast finished! +0ms
^C
Closing Cast to TV...
  bridge Closing node server +15s
  bridge Closed file watcher +4ms
  bridge Removed top bar indicator +10ms
  bridge Cleaned selection temp file +0ms
Cast to TV closed successfully

```
The log is saying stopped, but the video keeps playing.

**Comment by Rafostar** [comment]
> The log is saying stopped, but the video keeps playing. Pausing, scrubbing and volume control works tough.

The app closed, so how do you control it exactly?

**Comment by deisi** [comment]
I closed it after some seconds with Ctl+c, or what do you mean?

**Comment by Rafostar** [comment]
You said that video keeps playing and pausing, scrubbing and volume control works. They cannot work after app is closed. How do you control them after closing app?

**Comment by Rafostar** [comment]
Download from git master `chromecast.js` file inside `node_scripts` folder, copy and replace it in your extension installation, reboot PC and check if problem still exists.

**Comment by deisi** [comment]
> You said that video keeps playing and pausing, scrubbing and volume
control works

Now I understand. Well this I tested at another session that I did not
attached the debug log of. I was playing around with what works and what
not. So I just appended the log of a clean try, where I tried to stop the
video, but it kept playing.

However when stopping doesn't work and I don't want to wait for the end of
the video, I use https://extensions.gnome.org/extension/1955/cast-control/
to stop the video and go on.

Rafostar <notifications@github.com> schrieb am Do., 5. Sep. 2019, 23:35:

**Comment by Rafostar** [comment]
The above commit might help with stop button not actually stopping. But looking at your logs, I can see that everything is working exactly like it is supposed to.

From logs:
> chromecast New session OK +0ms

Session is sucessfuly created and verified. Good.

> bridge New remote contents: {"action":"STOP"} +16s
  chromecast Signal from remote. ACTION: STOP +10s

Remote is working exactly as expected and passes STOP command through extension bridge.

> chromecast Closing cast session... +0ms

This only happens when session was created successfully, no error or connection problem occurred during playback.

When closing function is executed it sends close signal to Chromecast and closes socket. Unfortunately at this point Chromecast does not send back any response if session is actually closed or not. The extension just assumes that after sending this signal to Chromecast it did stop as it was supposed to and hides the remote.

I never experienced any problems like you have and my extension is available for almost a year now. I always get at least few downloads of it every day, so I think someone else would report this kind of problem earlier. From my point of view it looks like something other in your network (it might be even on other device) keeps connection active with Chromecast and prevents it from closing cast session.

**Comment by deisi** [comment]
I think https://github.com/Rafostar/gnome-shell-extension-cast-to-tv/commit/8ea457d9aaac079581d10eedc6c4de89208c3680 helped. At least now it stoped the video up on klicking the stop button. The only thing is that it still not goes back to the default chromecast screen but rather keeps showing the cast symbol.

**Comment by Rafostar** [comment]
@deisi Did you try removing `cast-control` and following steps I described in my last comment edit?

**Comment by deisi** [comment]
I did as you said. Removed cast-control. Uninstalled modules and rebooted. Turned off chromecast.
Things stat still have some connection to chromecast:

- Android Phone via google Home (I guess that is common)
- Home Assistant  https://www.home-assistant.io/components/cast/

Letter is not so common I guess. Maybe these two are interfering somehow. Just so I understand, if I close the playback and the remote sing is still on the screen, it meas that the chromecast thinks there is still a tcp connection?

**Comment by Rafostar** [comment]
> Just so I understand, if I close the playback and the remote sing is still on the screen, it meas that the chromecast thinks there is still a tcp connection?

Yes.

When you press stop button, my app sends a close signal to Chromecast, then Chromecast closes the tcp connection, becouse there are no more clients using this connection, it should automatically go back to backdrop (showing pictures). For some reason unknown to me your Chromecast ignores it.

**Comment by Rafostar** [comment]
@deisi So, removing `cast-control` did not help?

**Comment by deisi** [comment]
Sadly no.

Rafostar <notifications@github.com> schrieb am So., 8. Sep. 2019, 16:48:

**Comment by Rafostar** [comment]
**Good news:** I managed to find the cause. :smile: 
**Bad news:** The code in extension works correctly, but my app controls Chromecast through external node module (it has a bug that causes this problem) and I am not the creator of the code inside it (only forked it cause it was abandoned some time ago) and it is very outdated. Going through all that outdated mess would be pointless. :disappointed: 

I decided to write my own controller that suits my needs. So the fix is coming, but it will require a LOT of work and time through.

**Comment by deisi** [comment]
:) Nice. First step is finding the problem. I might be able to help you a little more in the future. I'm making myself familiar with your addon more and more. I started with the python part because that I' m most familiar with. JavaScript I'm not so experienced with, but eventually I will get there. Maybe you have a suggestion for me what I could help with. Say something easy that would take you a couple of minims, so I can try and get it to work.

**Comment by Rafostar** [comment]
Everything mentioned above should be working now with latest git master from merge #78.

The new [chromecast-controller](https://github.com/Rafostar/chromecast-controller) that I recently made, should work better and faster than the one used up until now and Chromecast should now always close session properly and return to BackDrop.

When playing incompatible file you should see a notification on desktop saying which file was unplayable. When casting multiple files extension should automatically load next file then.

BTW: New version includes new playlist feature (file queue). Click on any item from the list to play it. New files can be added to playlist while playing as long as they are of the same media type (video, music or picture). Items order can be changed via simple "Drag and Drop". Drop item anywhere outside the playlist to remove it from queue.

**Comment by deisi** [comment]
Awesome :) I will gladly check out during the weekend. I let you know of my
findings.

PS. I'm still trying to get into extension development for gnome shell, but
Gosch they make it hard. There is only very distributed and outdated
documentation available. Everything has to be pieced together in time
consuming work. By now I think looking at commit messages and code is
almost the only way of getting a hang on it.

Rafostar <notifications@github.com> schrieb am Fr., 27. Sep. 2019, 11:19:

**Comment by deisi** [comment]
> Chromecast should now always close session properly and return to BackDrop

I just tested and it works.

> When playing incompatible file you should see a notification on desktop saying which file was unplayable. 

I tested with a single file with vp9 video and opus audio codec. Audio was playing, video of course not. However there was no notification. I tried to find a video that has an unsupported audio codec, but I actually have a hard time finding one.

-    HE-AAC
-   LC-AAC
-   MP3
-   Vorbis
-   WAV (LPCM)
-   FLAC (up to 96kHz/24-bit)
-   Opus

is a fairly complete list ....
I then tried the same within a playlist, but observed the same.

> New version includes new playlist feature

I tested as well. Works as intended. However would it be difficult to also add the ability to select a list of files at the select video step right away. Basicaly send a list of files instead of a single file in the beginning? I guess the question would be in what order, but maybe once can work something out like alphabeticaly, or its possible to retrieve in what order the elements were selected.

 To me this felt more natural as it was what I actually tried before reading your post again.

**Comment by Rafostar** [comment]
@deisi If your Chromecast plays the audio then it "thinks" he is able to play the file and does not report back any errors. In this case there is nothing I can do about this. I have the 1st gen Chromecast and it doesn't do that, at least I tested it on the video you send me and it went back to BackDrop and extension showed a notification. Like I say, I don't know what model you have, but if it plays audio and does not report back any errors, nothing can be done about it.

> Basicaly send a list of files instead of a single file in the beginning

This was always possible. Just select multiple files. If you are selecting with extension file-chooser just hold `Ctrl` or `Shift` when selecting with mouse. In Nautilus this works too as long as files are of the same type (video, music or picture). You can also cast video with external subtitles from Nautilus by selecting exactly one video and one subtitles file on right click.

**Comment by deisi** [comment]
> This was always possible.

Okay, then it was just bad luck or something when I tried it. 

>  file and does not report back any errors.

I understand. I thought so, but I wanted to report just in case. 
I guess we can close this issue, as the remote control issue is solved.
