### ISSUE TITLE
Dependency missing on ubuntu 19.10 daily

### ISSUE THREAD

**Issue by deisi** [Rafostar/gnome-shell-extension-cast-to-tv#67]
To run `make install` on ubuntu 19.10 daily I needed to also install `gettext`. Otherwise I was getting: `/bin/sh: 3: msgfmt: not found`

I don't know if this will be the same once ubuntu 19.10 is released.

**Comment by Rafostar** [comment]
`gettext` is only needed for compiling translations when installing from source. Thought it should be preinstalled. I will add it to the wiki installation page.
