### ISSUE TITLE
Fails on gnome 3.34 due to No signal value-changed on Gjs_Slider

### ISSUE THREAD

**Issue by deisi** [Rafostar/gnome-shell-extension-cast-to-tv#76]
I guess they again changed stuff for the addons....

**Comment by Rafostar** [comment]
Yes. I am aware of it. This is only one of many errors on GNOME 3.34 (if you fix that one another appears, as shell extensions stop processing the rest of code once error occurs).

Latest Shell version has a LOT of breaking changes for almost all extensions.

Don't worry through. I already got everything in extension code fixed (even with new features :smile: ). The only missing part is the finishing of new [chromecast-controller](https://github.com/Rafostar/chromecast-controller) code. Once I finish fixing #65 I will merge everything to git master.

**Comment by deisi** [comment]
Could you point me to any kind of breaking changes section for extension authors? I tried to find some and be helpful, but I didn't really find any, or are the gnome guys just breaking random stuff and one has to find out what changed by try and error?

**Comment by Rafostar** [comment]
> Could you point me to any kind of breaking changes section for extension authors?

Nothing like that exists.

> are the gnome guys just breaking random stuff and one has to find out what changed by try and error?

Yes. They don't care. Many people gave up on updating their extensions due to this.

**Comment by Rafostar** [comment]
Should be working now with latest git master.

**Comment by deisi** [comment]
> Should be working now with latest git master.

tested and does :)
