### ISSUE TITLE
3279a fails on gnome shell 3.32

### ISSUE THREAD

**Issue by deisi** [Rafostar/gnome-shell-extension-cast-to-tv#80]
Now that it is fixed for 3.34 it fails on 3.32 xD
LG ist saying:

```
GObjectregisterClass() used with invalid base class is (PopupBaseMenuItem)
```

**Comment by Rafostar** [comment]
God, really? I tested it on 2.26 and 3.34, so I assumed it should work on all versions in between. I know where this error is coming from. I will check possible solution during the weekend.

**Comment by deisi** [comment]
Don't worry. After starting to read about gnome shell extensions I'm actually impressed that you get it to work on more then one version. This level of stability/documentation is just a pain.

**Comment by Rafostar** [comment]
I think that it is fixed now. Besides `GObject.registerClass` there were some problems with playlist drag and drop. Especially the empty field (with insert icon) that should appear below dragged item across the playlist. I do not have a PC with permanently installed 3.32, so please check if it works for me.

I just hope nothing more is broken and I will be able to release the next stable version before Ubuntu/Fedora 3.34 releases :pray:

**Comment by Rafostar** [comment]
Tested myself and appears to be working just fine now.
