### ISSUE TITLE
No file chooser dialog

### ISSUE THREAD

**Issue by snex** [Rafostar/gnome-shell-extension-cast-to-tv#85]
Just upgraded to the latest version of cast-to-TV, and now I can't get a file chooser dialog when I try to cast anything. Not sure if/where the extension writes to logs so I don't have any logging info.

Gnome version 3.28.2

**Comment by snex** [comment]
For whatever reason, rebooting fixed.

**Comment by Rafostar** [comment]
After this update npm modules installation (from extension settings) must be run again. Due to some changes in code to support GNOME 3.34 few functions in extension are behaving differently than before, therefore the reboot was probably needed.
