### ISSUE TITLE
Support for GVFS in Nautilus Integration 

### ISSUE THREAD

**Issue by mlmilliman** [Rafostar/gnome-shell-extension-cast-to-tv#86]
I just upgraded to version 11 and installed the Nautilus integration. The Python scrips are all in the proper place and appear in the context menu when a media file is on a system mounted drive but not when GVFS is used. I use GVFS to connect to my NAS and it would be useful if the Nautilus integration supported GVFS too.

**Comment by Rafostar** [comment]
Done! Although I do not have a NAS. Please check this for me, ok?
