### ISSUE TITLE
Error on fedora 31

### ISSUE THREAD

**Issue by snaggen** [Rafostar/gnome-shell-extension-cast-to-tv#87]
Using Fedora with Gnome 3.34.1 I can't get the extension to start, when I install it I get ERROR. Looking at Looking Glass I see the error 
Error: No signal 'value-changed' on object 'Gjs_Slider'

**Comment by snaggen** [comment]
And just to be clear, I use the latest version (11) of the extension.

**Comment by Rafostar** [comment]
> Error: No signal 'value-changed' on object 'Gjs_Slider'

Impossible. I removed 'value-changed' from the code in v11. Please remove your current installation manually with:
```
rm -rf ~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com
```
Then reinstall extension and reboot.

**Comment by snaggen** [comment]
This is weird. I uninstalled the extension by rm the directory and reinstalled it.... however, gnome-shell must have kept the old one in memory or something. Did rm of the dir, rebooted and reinstalled and now it works so the error was indeed between my chair and keyboard.
