### ISSUE TITLE
Audio stops unexpectedly

### ISSUE THREAD

**Issue by sellicott** [Rafostar/gnome-shell-extension-cast-to-tv#89]
I am using version 11 of the cast extension and Gnome version 3.34 on Arch Linux.
When casting audio files, the stream will cut out midway through. I did not see any errors emitted in looking glass.

Thanks!

**Comment by Rafostar** [comment]
Turn off cast service (from this extension top bar menu). TV indicator icon should disappear from top bar. Then do the following:
```
cd ~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts
DEBUG=bridge,chromecast node server
```
After running, extension menu and indicator should reappear.
Try reproducing your problem and see what happens in the terminal output. You can stop the terminal process anytime with `Ctrl+c` buttons.

**Comment by sellicott** [comment]
After doing that I get this output from the terminal at some point after starting the cast. I tried this with a few different audio files and formats, all with a similar output but with slightly different delays before stopping.

```
  chromecast Cast started +3s
  chromecast Playback autostart +1ms
  chromecast Started status interval +0ms
  chromecast Obtained volume value: 1 +65ms
  chromecast-controller Player close event +2m
  chromecast-controller Closing client... +0ms
  chromecast-controller Player check: inactive +0ms
  chromecast-controller Closed client +0ms
  chromecast Stopped status interval +2m
  chromecast Cast finished due to close event! +7ms
```

It does not seem like there is any error, it just decides to close for some reason.

**Comment by Rafostar** [comment]
Thanks for the logs. There does not seem to be any error occurring inside my app. The `close event` usually happens when file ends or someone else presses stop from another device.

If possible could you send me the output of:
```
DEBUG=castv2* node server
```

**Comment by sellicott** [comment]
I tried it again and it worked correctly today. I don't really know what changed but it probably specific to my system so I am going to close the issue. Thank you for you help.
