### ISSUE TITLE
Autoplay for Image list

### ISSUE THREAD

**Issue by jsuarez314** [Rafostar/gnome-shell-extension-cast-to-tv#96]
When is casted a image list, this do not have autoplay, it is necessary change each image clicking the button ">>" from the PC. 

This extension is wonderful, thanks you!

**Comment by Rafostar** [comment]
@jsuarez314 
Thanks. Automatic picture slideshow is already done in latest git source code as requested in #84. The git code still has a few bugs that need to be resolved before creating next stable release.

**Comment by jsuarez314** [comment]
Thanks!
